# Let travis know the language it needs to run
language: node_js

env:
  - CI=false

node_js:
  - "stable"

cache:
  directories:
  - node_modules

script:
  - npm run build --max_old_space_size=8192

notifications:
  email:
    recipients:
      - $USER_1
      - $USER_2

deploy:
  provider: script
  script: bash scripts/docker_push
  on:
    branch: master



deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: build
  on:
    branch: master


